specialChar_mapping = {
    "~": "NORMAL",
    "!": "NORMA",
    "@": "NORMAL",
    "#": "NORMAL",
    "$": "NORMAL",
    "%": "NORMAL",
    "^": "NORMAL",
    "&": "NORMAL",
    "*": "NORMAL",
    "(": "NORMAL",
    ")": "NORMAL",
    "_": "NORMAL",
    "+": "NORMAL",
    "{": "NORMAL",
    "}": "NORMAL",
    "|": "NORMAL",
    ":": "NORMAL",
    '''"''': "NORMAL",
    "<": "NORMAL",
    ">": "NORMAL",
    "?": "NORMAL",
    "\\": "NORMAL",
    "`" : "NORMAL",
    "-" : "NORMAL",
    "=" : "NORMAL",
    "[" : "NORMAL",
    "]" : "NORMAL",
    ";" : "NORMAL",
    "'" : "NORMAL",
    "," : "NORMAL",
    "." : "NORMAL",
    "/" : "NORMAL"
}
